### PR TITLE
Submit WIP Draft for Distribution of EOS Inflation Back to Voters That Have Voted For At Least 21 Block Producers

### PR DESCRIPTION
**Pull request by robrigo**
This is a WIP, just wanted to provide visibility into the draft EEP proposal.

### CODE REVIEW

**Comment by abourget** [comment]
That's great!

Have you guys thought of a way to implement that?

I really want to merge that asap.. but also want to set the tone for the depth of the proposals. What do you think?

**Comment by robrigo** [comment]
Hi Alex, thanks for asking!

@abourget the implementation is on going, I wouldn't merge this in until the first pass of the whole EEP is added. I just wanted to put up the working draft for visibility.

**Comment by abourget** [comment]
Excellent!

**Comment by robrigo** [comment]
There was a flaw in this design- that is, incentivizing voters to hold without making their stake resources also usable would perpetuate CPU shortages. It's important to combine the voting incentive with resource leasing ala REX.

**Pull request closed without merging**
